//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Essay
    {
        public long ID { get; set; }
        public Nullable<long> IDUser { get; set; }
        public Nullable<long> IDSession { get; set; }
        public string File { get; set; }
        public Nullable<double> Score { get; set; }
        public Nullable<System.DateTime> DateCmt { get; set; }
        public Nullable<System.DateTime> RepDate { get; set; }
        public string Detail { get; set; }
        public string Comment { get; set; }
    
        public virtual Session Session { get; set; }
        public virtual User User { get; set; }
    }
}
